source "${HOME}/.profile"

source_file "$cfg_zsh/options.sh" 
source_file "$cfg_zsh/aliases.sh" 
source_file "$cfg_zsh/functions.sh"
source_file "$cfg_zsh/$SHELL_NAME/init.sh"
source_file "$cfg_zsh/tools/fzf.sh"
source_file "$cfg_zsh/$SHELL_NAME/plugins.sh"
source_file "$cfg_zsh/tools/perl.sh"
source_file "$cfg_zsh/tools/ruby.sh"
