source "${HOME}/.profile"

source_file "$cfg_sh/options.sh" 
source_file "$cfg_sh/aliases.sh" 
source_file "$cfg_sh/functions.sh"
source_file "$cfg_sh/$SHELL_NAME/init.sh"
source_file "$cfg_sh/tools/fzf.sh"
source_file "$cfg_sh/$SHELL_NAME/plugins.sh"
source_file "$cfg_sh/tools/perl.sh"
source_file "$cfg_sh/tools/ruby.sh"
